### ISSUE TITLE
Data to port from msdata

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsDataHub#1]
@jorainer - could you provide me with a list of datasets that need to be ported from `msdata` into `MsDataHub`.

**Comment by jorainer** [comment]
Please add:

- files in the TripleTOF-SWATH folder: PestMix1_DDA.mzML, PestMix1_SWATH.mzML
- files in the sciex folder: 20171016_POOL_POS_1_105-134.mzML, 20171016_POOL_POS_3_105-134.mzML
- cdf/ko15.CDF

thanks

**Comment by lgatto** [comment]
Do you have the provenance of these?

**Comment by jorainer** [comment]
The TripleTOF files are from Michael Witting (Helmholtzzentrum Muenchen), the sciex files are mine, the cdf file is one file from the `faahko` R package (I believe that's a subset of data files from a publication - old one from 2006).

**Comment by jorainer** [comment]
I believe they should be documented in the `msdata` package (description etc)

**Comment by lgatto** [comment]
I meant where can I get the raw files, assuming there are publicly available, in a database for example. But apparently not. 

There isn't much documentation in `msdata`.

**Comment by jorainer** [comment]
no, these files are in no public repo, only within the package. Regarding docs: I can add/expand the documentation for these files.

**Comment by lgatto** [comment]
Will open an issue and ask you to update the man pages once I'm there. Thanks!
